### ISSUE TITLE
Issue when trying to run serverless-policy

### ISSUE THREAD

**Issue by babyhuey** [dancrumb/generator-serverless-policy#2]
$ yo serverless-policy
/usr/lib/node_modules/generator-serverless-policy/generators/app/index.js:143
module.exports = class extends Generator {
                           ^^^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.defineProperty.get [as serverless-policy:app] (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:40:23)
    at Store.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/store.js:64:35)
    at Environment.get (/usr/lib/node_modules/yo/node_modules/yeoman-environment/lib/environment.js:262:16)

**Comment by babyhuey** [comment]
https://github.com/dancrumb/generator-serverless-policy/pull/3
